### PR TITLE
Upgrade binaries from 4.4.0 to 4.9.1.

### PR DESCRIPTION
**Pull request by raf64flo**
Upgrade SolR binary from 4.4.0 to 4.9.1.

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
Thanks @raf64flo

**Comment by dbolser-ebi** [comment]
Should I re-index all the data after making this change?

**Comment by raf64flo** [comment]
Thanks for the merge.

Does it work better now?

**Comment by raf64flo** [comment]
Oh sorry Dan I didn't see your question. To be honest, I don't know if reindexing is required. I took a quick look at release notes (https://lucene.apache.org/solr/4_9_1/changes/Changes.html#v4.9.0.upgrading_from_solr_4.8) but I didn't get any hint concerning that. Let's give a try with current indexed data.
But since there is no major version jump, I believe it should work out of the box.

**Comment by raf64flo** [comment]
@dbolser-ebi were you able to fix the problem you faced thanks to the binaries upgrade?

**Pull request merged**
